name: PR

on:
  pull_request:
    branches: [ master ]
    types:
      - opened
      - reopened
      - edited
      - synchronize
  issue_comment:
    types: [ edited ]

jobs:
  preview:
    name: Release-Notes Preview
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - run: |
        git fetch --prune --unshallow --tags
    - uses: snyk/release-notes-preview@v1.6.1
      with:
        releaseBranch: master
      env:
        GITHUB_PR_USERNAME: ${{ github.actor }}
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  conventional-title:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: agenthunt/conventional-commit-checker-action@v1.0.0
